# 默认
exception-default-message: 未知错误
# 需要登录
exception-need-login-message: 您需要登陆后才能进行该操作
# 404
exception-not-found-message: 您访问的地址不存在
# 未知账号
exception-unknown-account-message: 账号不存在
# 凭证不正确
exception-incorrect-credentials-message: 用户名或密码错误
# 账户被锁定
exception-locked-account-message: 您的账户已被冻结
# 没有权限
exception-no-authentication-message: 您没有权限做此操作
# 不支持的令牌
exception-unsupported-token-message: 身份异常
# 账户被禁用
exception-disabled-account-message: 您的账户已被禁用
# 过渡尝试
exception-excessive-attempts-message: 您的操作太频繁,请稍后再试
# 并行访问
exception-concurrent-access-message: 您的账户已在别处登录,请退出后重试
# 账户异常
exception-account-message: 账户异常
# 凭证已过期
exception-expired-credentials-message: 您的账户凭据已过期
# 证书异常
exception-credentials-message: 账户异常
# 认证异常
exception-authentication-message: 账户认证失败
# 未经认证
exception-unauthenticated-message: 您没有权限做此操作
# 未经授权
exception-unauthorized-message: 您没有权限做此操作
# Feign 接口调用失败
exception-feign-message: 请求超时,请稍后再试
# 第三方登录异常
exception-third-party-login-message: 用户中心登录失败